//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONLINEFOODMOLL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int sno { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public System.DateTime date { get; set; }
        public string p_name { get; set; }
        public int p_price { get; set; }
        public int p_qty { get; set; }
        public int p_bill { get; set; }
    }
}
