//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONLINEFOODMOLL.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Photo
    {
        public int p_id { get; set; }
        public string p_name { get; set; }
        public int p_price { get; set; }
        public string image_path { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
